<?php
/**
 * @file
 *
 *
 *
 *
 */

// Load fedora_item.inc from the fedora_repository module in the api folder.
module_load_include('inc', 'fedora_repository', 'api/fedora_item');

/**
 * Implementation of hook_nodeapi().
 */
function islandora_upload_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
global $user;
  switch  ($op)  {
    case  'delete':
      // if user has permission user purge else use delete
      islandora_upload_delete_fedora_objects($node, $user->uid);
      break;

    case  'insert':
      //need to grab all files attached to node
      //db_query("INSERT INTO {node_fedora_objects} (NID, PID) VALUES (%d, %d)", $node->nid, "232");
      db_query("INSERT INTO {node_fedora_objects} (nid,pid) VALUES ('" . $node->nid . "','2555')");
      break;

    case  'update':
      break;

    case 'validate':
      //check file mimes?
      //use form_set_error().
      break;
  }
}

/**
 * When a Drupal Node is deleted this function will delete
 * all associated Fedora Objects
 *
 * @param $node
 *   A node object.
 * @param $uid
 *   The current User ID. (This is the user deleting the node)
 *
 */
function islandora_upload_delete_fedora_objects($node, $uid) {

  //Grab all pid attached to the drupal node
  $sql = "SELECT pid FROM {node_fedora_objects} WHERE nid = '" . $node->nid . "'";
  $results = db_query($sql);

  while ($PID = db_result($results)) { // Get the next result, which will/must always be a single field
    $fedora_item = new Fedora_Item($PID);
    //check to see if the fedora object exists, if exists 1 is returned.
    if  ($fedora_item->exists())  {
      $state = 'D'; //Set the object to deleted
      $dsid = $PID; //I think this is distinct identifier
      $log_message = "Node {NID:" . $node->nid . "} created by {UID:" . $node->uid . "} which is associate with this object has been deleted by user {" . $uid . "}.";
      $fedora_item->set_datastream_state($dsid, $state, $log_message);
    }
  }
  db_query("DELETE FROM {node_fedora_objects} where nid = '" . $node->nid . "'");
}
/**
 * When a Drupal Node is deleted this function will purge
 * all associated Fedora Objects
 *
 * @param $node
 *   A node object.
 * @param $uid
 *   The current User ID. (This is the user deleting the node)
 *
 */
function islandora_upload_purge_fedora_objects($node, $uid) {

  //Grab all pid attached to the drupal node
  $sql = "SELECT pid FROM {node_fedora_objects} WHERE nid = '" . $node->nid . "'";
  $results = db_query($sql);

  while ($PID = db_result($results)) { // Get the next result, which will/must always be a single field
    $fedora_item = new Fedora_Item($PID);
    //check to see if the fedora object exists, if exists 1 is returned.
    if  ($fedora_item->exists())  {
      $log_message = "Node {NID:" . $node->nid . "} created by {UID:" . $node->uid . "} which is associate with this object has been purged by user {" . $uid . "}.";
      $fedora_item->purge($log_message, TRUE); //remove the fedora object
    }
  }
  db_query("DELETE FROM {node_fedora_objects} where nid = '" . $node->nid . "'");
}

/**
 * Implementation of hook_help().
 */
function islandora_upload_help($path, $arg) {
  if ($path == 'admin/help#islandora_upload') {
    $txt  =  'This module is used to sync Drupal Nodes with Fedora Objects.';
    $replace  =  array();
    return  '<p>' . t($txt, $replace) . '</p>';
  }
}

function islandora_upload_form_alter(&$form, $form_state, $form_id) {

}

